version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo

    volumes:
      - mongo-data:/data/db
    restart: always
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
       ME_CONFIG_MONGODB_ADMINPASSWORD: password
       ME_CONFIG_MONGODB_SERVER: mongodb
       ME_CONFIG_BASICAUTH_USERNAME: admin
       ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes:
      - mongodb-data

  backend:
    image: react-app-back
    container_name: react-app-back
    ports: 
      - 3001:5000
    restart: always
  frontend:
    image: react-app-front 
    container_name: react-app-front 
    ports: 
      - 3000:80
    restart: always
networks:
  default:
    external: 
      name: mongo-network
volumes:
  mongo-data: 
    driver: local




# version: '3'
# services:
#   react-app:
#     image: react-app-back
#     container_name: react-app-back
#     environment: 
#       - MONGODB_CONNSTRING=mongodb://AzureDiamond:hunter2@mongodb
#     ports:  
#       - 3001:5000
#   mongodb:
#     image: mongo:5.0
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
#       - MONGO_INITDB_ROOT_PASSWORD=hunter2
#   frontend:
#     image: react-app-front 
#     container_name: react-app-front 
#     ports: 
#       - 3000:80
#     restart: always
# networks:
#   default:
#     external: 
#       name: mongo-network
# volumes:
#   mongo-data: 
#     driver: local

# version: '3.1'
# services:
#   mongo:
#     image: mongo
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: password

#   mongo-express:
#     image: mongo-express
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#       ME_CONFIG_MONGODB_ADMINPASSWORD: password

#   backend:
#     image: react-app-back
#     container_name: react-app-back
#     environment: 
#       - MONGODB_CONNSTRING=mongodb://admin:password@mongo:27017/
#     ports: 
#       - 3001:5000
#     restart: always
#   frontend:
#     image: react-app-front 
#     container_name: react-app-front 
#     ports: 
#       - 3000:80
#     restart: always
# networks:
#   default:
#     external: 
#       name: mongo-network
# volumes:
#   mongo-data: 
#     driver: local