version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
  

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: admin
       ME_CONFIG_MONGODB_ADMINPASSWORD: password
       ME_CONFIG_MONGODB_SERVER: mongodb
       ME_CONFIG_BASICAUTH_USERNAME: admin
       ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    networks: 
      - app-network

  backend:
    image: react-app-back
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: react-app-back
    ports: 
      - 5000:5000
    restart: always
    networks: 
      - app-network



  frontend:
    restart: always
    image: react-app-front
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: react-app-front 
    ports: 
      - 3000:3000
    
    networks: 
      - app-network
    depends_on:
      - backend


  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 808:80
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
volumes:
  mongodb-data: 
    driver: local



