version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    restart: always
  backend:
    image: react-app-back
    container_name: react-app-back
    ports: 
      - 3001:5000
    restart: always
  frontend:
    image: react-app-front 
    container_name: react-app-front 
    ports: 
      - 3000:80
    restart: always
networks:
  default:
    external: 
      name: mongo-network
volumes:
  mongo-data: 
    driver: local